backend/models/Curriculum.php
<?php

namespace backend\models;

use common\models\ArtBlogBase;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "{{%curriculum}}".
 *
 * @property int $id
 * @property string $avatar
 * @property string $name
 * @property string $last_name
 * @property string $art_alias
 * @property string $birthday
 * @property string $birthplace
 * @property string $current_place
 * @property string $biography
 * @property string $events
 * @property string $created_at
 * @property string $updated_at
 * @property int $status
 *
 * @property Artwork[] $artworks
 * @property Contact[] $contacts
 * @property Review[] $reviews
 */
class Curriculum extends ArtBlogBase
{
    public $file;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%curriculum}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'last_name', 'art_alias'], 'required'],
            [['birthday', 'created_at', 'updated_at'], 'safe'],
            [['biography', 'events', 'avatar'], 'string'],
            [['name', 'last_name', 'art_alias', 'birthplace', 'current_place'], 'string', 'max' => 255],
            [['status'], 'string', 'max' => 1],
            [['file'], 'file'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'avatar' => 'Perfil',
            'file' => 'Perfil',
            'name' => 'Nombre',
            'last_name' => 'Apellidos',
            'art_alias' => 'Alias',
            'birthday' => 'Cumpleaños',
            'birthplace' => 'Lugar de Naciemiento',
            'current_place' => 'Lugar Actual',
            'biography' => 'Biografía',
            'events' => 'Eventos',
            'created_at' => 'Fecha de Creado',
            'updated_at' => 'Fecha de Actualizado',
            'status' => 'Estado',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArtworks()
    {
        return $this->hasMany(Artwork::className(), ['author_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContacts()
    {
        return $this->hasMany(Contact::className(), ['curriculum_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReviews()
    {
        return $this->hasMany(Review::className(), ['curriculum_id' => 'id']);
    }

    /**
     * Manage Created and Update times
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        //Manage Created and updated times
        if ($this->isNewRecord) {
            $this->created_at = date("Y-m-d H:i:s");
            $this->updated_at = date("Y-m-d H:i:s");

        } else {
            $this->updated_at = date("Y-m-d H:i:s");
        }

        //If we have a new Active Curriculum, then the las activated has to be changed
        if ($this->isActive()) {
            $currID = Curriculum::getActiveCurriculumID();
            if ($currID > 0) {
                Yii::$app->db->createCommand()
                    ->update('curriculum', ['status' => Curriculum::STATUS_INACTIVE], ['id' => $currID])->execute();
            }
        }

        $this->file = UploadedFile::getInstance($this, 'file');

        if($this->isNewRecord && !isset($this->file)){
            $this->addError('file',"Este campo no puede estar vacío.");
            return false;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /** Return true if the current model is Active, false other wise
     * @return bool
     */
    public function isActive()
    {
        return $this->status == self::STATUS_ACTIVE;
    }

    /** Return true if avatar has some value, false other wise
     * @return bool
     */
    public function hasAvatar()
    {
        return isset($this->avatar) && !empty($this->avatar);
    }

    /** Return a mapped array of Curriculum in [id=>name] format
     * @return array
     */
    public static function getMappedCurriculums()
    {
        return ArrayHelper::map(self::find()->where(['status' => self::STATUS_ACTIVE])->all(), 'id', 'name');
    }

    /** Return the only active Curriculum
     * @return array|null|\yii\db\ActiveRecord
     */
    public static function getActiveCurriculum()
    {
        return self::find()->where(['status' => self::STATUS_ACTIVE])->one();
    }

    /** Return the ID of the only active Curriculum
     * @return integer
     */
    public static function getActiveCurriculumID()
    {
        if (($model = self::find()->where(['status' => self::STATUS_ACTIVE])->one()) !== null) {
            return $model->id;
        }

        return -1;
    }

    /** Returns the relative path to avatar file
     * @return string
     */
    public function generateFileRoute()
    {
        return Yii::$app->getHomeUrl() .
        '../../common/resources/curriculum_files/Curriculum_' . $this->id . "/" . $this->avatar;
    }

    public function beforeDelete()
    {
        //We need to remove files generated trough model live cycle 
        $directory_resources = '../../common/resources/curriculum_files/Curriculum_' . $this->id;
        FileHelper::removeDirectory($directory_resources);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}

frontend/models/Curriculum.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "{{%curriculum}}".
 *
 * @property int $id
 * @property int $user_id
 * @property string $name
 * @property string $last_name
 * @property string $art_alias
 * @property string $birthday
 * @property string $birthplace
 * @property string $current_place
 * @property string $biography
 *
 * @property Artwork[] $artworks
 * @property Contact[] $contacts
 * @property User $user
 * @property Review[] $reviews
 */
class Curriculum extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%curriculum}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'name', 'last_name', 'art_alias'], 'required'],
            [['user_id'], 'integer'],
            [['birthday'], 'safe'],
            [['biography'], 'string'],
            [['name', 'last_name', 'art_alias', 'birthplace', 'current_place'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'name' => 'Name',
            'last_name' => 'Last Name',
            'art_alias' => 'Art Alias',
            'birthday' => 'Birthday',
            'birthplace' => 'Birthplace',
            'current_place' => 'Current Place',
            'biography' => 'Biography',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArtworks()
    {
        return $this->hasMany(Artwork::className(), ['author_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContacts()
    {
        return $this->hasMany(Contact::className(), ['curriculum_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReviews()
    {
        return $this->hasMany(Review::className(), ['curriculum_id' => 'id']);
    }
}

backend/controllers/CurriculumController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Curriculum;
use backend\models\CurriculumSearch;
use yii\helpers\FileHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * CurriculumController implements the CRUD actions for Curriculum model.
 */
class CurriculumController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Curriculum models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CurriculumSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Curriculum model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Curriculum model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Curriculum();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (!$this->manageFiles($model)) {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
            return $this->redirect(['index']);
        }
        
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Curriculum model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (!$this->manageFiles($model)) {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Curriculum model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Curriculum model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Curriculum the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Curriculum::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Change the status of Curriculum model with the param 'id'
     * @param $id integer The Curriculum ID to change it status
     * @return string
     * @throws NotFoundHttpException
     * @throws \yii\db\Exception
     */
    public function actionStatus($id)
    {
        if (Yii::$app->request->getIsAjax()) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            if (($model = $this->findModel($id)) !== null) {
                // There is only ONE active Curriculum, so we handle that condition
                if ($model->isActive()) {
                    //Just change it status
                    Yii::$app->db->createCommand()
                        ->update(Curriculum::tableName(), ['status' => Curriculum::STATUS_INACTIVE], ['id' => $id])->execute();
                } else {
                    //We need to update the current curriculum activated to disable it
                    $currID = Curriculum::getActiveCurriculumID();
                    if ($currID > 0) {
                        Yii::$app->db->createCommand()
                            ->update(Curriculum::tableName(), ['status' => Curriculum::STATUS_INACTIVE], ['id' => $currID])->execute();
                    }
                    //Only then we can change model to status Active
                    Yii::$app->db->createCommand()
                        ->update(Curriculum::tableName(), ['status' => Curriculum::STATUS_ACTIVE], ['id' => $id])->execute();
                }
            }
            return "Status has Changed";
        }

        return "ERROR: some error has intercept the operation.";
    }

    /** Manage the save or replace avatar file related with a Curriculum model
     * @param Curriculum $model
     * @return bool|int
     * @throws \yii\base\Exception
     * @throws \yii\db\Exception
     */
    protected function manageFiles(Curriculum $model)
    {
        $route = '../../common/resources/curriculum_files/Curriculum_' . $model->id . "/";
        if (!file_exists($route)) {
            FileHelper::createDirectory($route, 0777);
        }

        if (isset($model->file)) {
            if (isset($model->avatar) && file_exists($route . $model->avatar)) {
                unlink($route . $model->avatar);
            }
            $model->avatar = "Avatar_" . time() . "." . $model->file->getExtension();
            $model->file->saveAs($route . $model->avatar);
            return Yii::$app->db->createCommand()
                ->update(Curriculum::tableName(), ['avatar' => $model->avatar], ['id' => $model->id])->execute();
        }

        return true;
    }
}

backend/views/curriculum/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Curriculum */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="curriculum-form">

    <?php $form = ActiveForm::begin([
        'options' => ['enctype' => 'multipart/form-data']
    ]); ?>

    <?= $form->field($model, 'file')->widget(\kartik\widgets\FileInput::classname(), [
        'options' => ['accept' => 'image/*', 'multiple' => false],
        'pluginOptions' => [
            'showUpload' => false,
            'showRemove' => false,
            'showPreview' => !$model->isNewRecord && $model->hasAvatar(),
            'initialPreview' => [$model->generateFileRoute()],
            'initialPreviewConfig' => [
                ['caption' => $model->avatar],
            ],
            'initialPreviewAsData' => true,
            'overwriteInitial' => !$model->isNewRecord && $model->hasAvatar(),
            'initialCaption' => $model->isNewRecord ? "Seleccione un perfil" : $model->avatar,
            'browseIcon' => '<i class="glyphicon glyphicon-camera"></i> ',
            'browseLabel' => 'Seleccionar imagen'
        ],
    ]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'art_alias')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'birthday')->widget(\kartik\widgets\DatePicker::classname(), [
        'options' => ['placeholder' => 'Cumpleaños'],
        'pluginOptions' => [
            'format' => 'yyyy-mm-dd',
            'autoclose' => true
        ]
    ]) ?>
    <?= $form->field($model, 'birthplace')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'current_place')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'biography')->widget(\yii\redactor\widgets\Redactor::className(),[
        'clientOptions' => [
            'lang' => 'es',
            'plugins' => ['clips', 'fontcolor', 'imagemanager'],
            'placeholder'=>'Biografía personal'
        ]
    ]); ?>

    <?= $form->field($model, 'events')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'status')->widget(\kartik\widgets\SwitchInput::classname(), [
        'name' => 'status',
        'pluginOptions' => ['size' => 'medium',
            'onText' => 'Activo',
            'offText' => 'Inactivo',
        ],
    ]); ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']); ?>
        <?= Html::a('Cancelar', Yii::$app->request->getReferrer(), ['class' => 'btn btn-default']); ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/curriculum/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\CurriculumSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="curriculum-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'last_name') ?>

    <?= $form->field($model, 'art_alias') ?>

    <?= $form->field($model, 'birthday') ?>

    <?php // echo $form->field($model, 'birthplace') ?>

    <?php // echo $form->field($model, 'current_place') ?>

    <?php // echo $form->field($model, 'biography') ?>

    <?php // echo $form->field($model, 'events') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/curriculum/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Curriculum */

$this->title = 'Crear Currículo';
$this->params['breadcrumbs'][] = ['label' => 'Currículos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="curriculum-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/curriculum/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\CurriculumSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Currículos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="curriculum-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Crear Currículo', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(['id' => 'curriculumGrid']); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'options' => [
            'class' => 'table-responsive'
        ],
        'columns' => [
            [
                'attribute' => 'id',
                'value' => 'id',
                'contentOptions' => ['style' => 'width:5%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ],
            [
                'attribute' => 'name',
                'value' => 'name',
                'contentOptions' => ['style' => 'width:10%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ],
            [
                'attribute' => 'last_name',
                'value' => 'last_name',
                'contentOptions' => ['style' => 'width:10%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ],
            [
                'attribute' => 'art_alias',
                'value' => 'art_alias',
                'contentOptions' => ['style' => 'width:10%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ],
            [
                'attribute' => 'birthplace',
                'value' => 'birthplace',
                'contentOptions' => ['style' => 'width:10%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ],
            [
                'attribute' => 'current_place',
                'value' => 'current_place',
                'contentOptions' => ['style' => 'width:10%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ],
            [
                'attribute' => 'status',
                'filter' => ["1" => "Activo", "0" => "Inactivo"],
                'value' => function (\backend\models\Curriculum $model) {
                    $url = \yii\helpers\Url::to(['/curriculum/status', 'id' => $model->id]);
                    return \kartik\widgets\SwitchInput::widget([
                        'name' => 'status',
                        'value' => $model->status,
                        'pluginOptions' => [
                            'size' => 'mini',
                            'onText' => '<i class="glyphicon glyphicon-ok"></i>',
                            'offText' => '<i class="glyphicon glyphicon-remove"></i>',
                            'onColor' => 'success',
                            'offColor' => 'danger'
                        ],
                        'pluginEvents' => [
                            "switchChange.bootstrapSwitch" => "function() { 
                                    $.ajax('$url', {
                                        type: 'POST'
                                    }).done(function(data) {
                                        console.log(data);
                                        $.pjax.reload({container: '#curriculumGrid'});
                                    });
                                }",
                        ]
                    ]);
                },
                'format' => 'raw',
                'contentOptions' => ['style' => 'width:8%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Acciones',
                'contentOptions' => ['style' => 'width:6%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ]
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

backend/views/curriculum/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Curriculum */

$this->title = 'Actualizar Currículo: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Currículos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Actualizar';
?>
<div class="curriculum-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/curriculum/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Curriculum */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Curriculums', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="curriculum-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Crear', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Volver', ['index'], ['class' => 'btn btn-default']) ?>
        <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger pull-right',
            'data' => [
                'confirm' => 'Seguro desea eliminar este elemento?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute'=>'avatar',
                'value'=>Html::img($model->generateFileRoute(),
                    ['alt'=>$model->name,'title'=>$model->name, 'style'=>'width: 200px']),
                'format'=>'raw'
            ],
            'name',
            'last_name',
            'art_alias',
            'birthday',
            'birthplace',
            'current_place',
            [
                'attribute' => 'biography',
                'value' => $model->biography,
                'format' => 'html'
            ],
            'events:ntext',
            'created_at',
            'updated_at',
            [
                'attribute' => 'status',
                'value' => function (\backend\models\Curriculum $model) {
                    $url = \yii\helpers\Url::to(['/curriculum/status', 'id' => $model->id]);
                    return \kartik\switchinput\SwitchInput::widget([
                        'name' => 'status',
                        'value' => $model->status,
                        'pluginOptions' => [
                            'size' => 'mini',
                            'onText' => 'Activo',
                            'offText' => 'Inactivo',
                            'onColor' => 'success',
                            'offColor' => 'danger'
                        ],
                        'pluginEvents' => [
                            "switchChange.bootstrapSwitch" => "function() {
                                        $.ajax('$url', {
                                            type: 'POST'
                                        }).done(function(data) {
                                            console.log(data);
                                        });
                                    }",
                        ]
                    ]);
                },
                'format' => 'raw'
            ],
        ],
    ]) ?>

</div>