backend/models/Artwork.php
<?php

namespace backend\models;

use common\models\ArtBlogBase;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "{{%artwork}}".
 *
 * @property int $id
 * @property string $name
 * @property int $author_id
 * @property int $artwork_type_id
 * @property int $exhibition_id
 * @property int $technique_id
 * @property int $m_unit_id
 * @property string $file_name
 * @property string $abstract
 * @property string $description
 * @property string $release_date
 * @property int $availability
 * @property int $quantity
 * @property double $price
 * @property double $raiting
 * @property double $width
 * @property double $height
 * @property string $created_at
 * @property string $updated_at
 * @property int $status
 *
 * @property MeasurementUnit $mUnit
 * @property ArtworkType $artworkType
 * @property Exhibition $exhibition
 * @property Technique $technique
 * @property Curriculum $author
 * @property Review[] $reviews
 */
class Artwork extends ArtBlogBase
{
    public $file;

    const AVAILABILITY_STATUS = true;
    const UNAVAILABILITY_STATUS = false;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%artwork}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'artwork_type_id', 'technique_id', 'm_unit_id', 'abstract'], 'required'],
            [['author_id', 'artwork_type_id', 'exhibition_id', 'technique_id', 'm_unit_id', 'quantity'], 'integer'],
            [['description'], 'string'],
            [['file'], 'file'],
            [['release_date', 'created_at', 'updated_at'], 'safe'],
            [['price', 'raiting', 'width', 'height'], 'number'],
            [['name', 'file_name', 'abstract'], 'string', 'max' => 255],
            [['availability', 'status'], 'string', 'max' => 1],
            [['m_unit_id'], 'exist', 'skipOnError' => true, 'targetClass' => MeasurementUnit::className(), 'targetAttribute' => ['m_unit_id' => 'id']],
            [['artwork_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => ArtworkType::className(), 'targetAttribute' => ['artwork_type_id' => 'id']],
            [['exhibition_id'], 'exist', 'skipOnError' => true, 'targetClass' => Exhibition::className(), 'targetAttribute' => ['exhibition_id' => 'id']],
            [['technique_id'], 'exist', 'skipOnError' => true, 'targetClass' => Technique::className(), 'targetAttribute' => ['technique_id' => 'id']],
            [['author_id'], 'exist', 'skipOnError' => true, 'targetClass' => Curriculum::className(), 'targetAttribute' => ['author_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Nombre',
            'author_id' => 'Autor',
            'artwork_type_id' => 'Tipo de Obra',
            'exhibition_id' => 'Exhibición',
            'technique_id' => 'Técnica',
            'm_unit_id' => 'UM',
            'file_name' => 'Poster',
            'file' => 'Poster',
            'abstract' => 'Resumen',
            'description' => 'Descripción',
            'release_date' => 'Fecha de Exposición',
            'availability' => 'Disponibilidad',
            'quantity' => 'Cantidad',
            'price' => 'Precio',
            'raiting' => 'Raiting',
            'width' => 'Ancho',
            'height' => 'Alto',
            'created_at' => 'Fecha de Creado',
            'updated_at' => 'Fecha de Actualizado',
            'status' => 'Estado',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMUnit()
    {
        return $this->hasOne(MeasurementUnit::className(), ['id' => 'm_unit_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArtworkType()
    {
        return $this->hasOne(ArtworkType::className(), ['id' => 'artwork_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getExhibition()
    {
        return $this->hasOne(Exhibition::className(), ['id' => 'exhibition_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTechnique()
    {
        return $this->hasOne(Technique::className(), ['id' => 'technique_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(Curriculum::className(), ['id' => 'author_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReviews()
    {
        return $this->hasMany(Review::className(), ['artwork_id' => 'id']);
    }

    /**
     * Manage Created and Update times, initialize file object to be processed by controller
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        //Manage Created and updated times
        if ($this->isNewRecord) {
            $this->created_at = date("Y-m-d H:i:s");
            $this->updated_at = date("Y-m-d H:i:s");
            $this->author_id = Curriculum::getActiveCurriculumID();
        } else {
            $this->updated_at = date("Y-m-d H:i:s");
        }

        $this->file = UploadedFile::getInstance($this, 'file');

        if ($this->isNewRecord && !isset($this->file)) {
            $this->addError('file', "Este campo no puede estar vacío.");
            return false;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /** Return true if the current model is Active, false other wise
     * @return bool
     */
    public function isActive()
    {
        return $this->status == self::STATUS_ACTIVE;
    }

    /** Return true if poster (file_name) has some value, false other wise
     * @return bool
     */
    public function hasPoster()
    {
        return isset($this->file_name) && !empty($this->file_name);
    }

    /** Return if the current model is Available or Not
     * @return bool return true if is Active, false other wise
     */
    public function isAvailable()
    {
        return $this->availability == self::AVAILABILITY_STATUS;
    }

    /** Return a mapped array of Artworks in [id=>name] format
     * @return array
     */
    public static function getMappedArtworks()
    {
        return ArrayHelper::map(self::find()
            ->where(['status' => self::STATUS_ACTIVE])
            ->all(), 'id', 'name');
    }

    /** Returns the relative path to avatar file
     * @return string
     */
    public function generateFileRoute()
    {
        return Yii::$app->getHomeUrl() .
        '../../common/resources/artwork_files/Artwork_' . $this->id . "/" . $this->file_name;
    }

    public function beforeDelete()
    {
        //We need to remove files generated trough model live cycle 
        $directory_resources = '../../common/resources/artwork_files/Artwork_' . $this->id;
        FileHelper::removeDirectory($directory_resources);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function getDimension(){
        return $this->width . 'x' . $this->height . ' ' . $this->mUnit->name ;
    }
}

backend/controllers/ArtworkController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Artwork;
use backend\models\ArtworkSearch;
use yii\helpers\FileHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * ArtworkController implements the CRUD actions for Artwork model.
 */
class ArtworkController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Artwork models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ArtworkSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Artwork model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Artwork model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Artwork();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (!$this->manageFiles($model)) {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
            return $this->redirect(['index']);
        }

        if (!isset($model->status)) $model->status = Artwork::STATUS_ACTIVE;
        if (!isset($model->availability)) $model->availability = Artwork::AVAILABILITY_STATUS;

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Artwork model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (!$this->manageFiles($model)) {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Artwork model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Artwork model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Artwork the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Artwork::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Change the status of Artwork model with the param 'id'
     * @param $id integer The Artwork ID to change it status
     * @return string
     * @throws NotFoundHttpException
     * @throws \yii\db\Exception
     */
    public function actionStatus($id)
    {
        if (Yii::$app->request->getIsAjax()) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            if (($model = $this->findModel($id)) !== null) {
                Yii::$app->db->createCommand()
                    ->update('artwork', [
                        'status' => $model->isActive() ? Artwork::STATUS_INACTIVE : Artwork::STATUS_ACTIVE
                    ], ['id' => $id])->execute();

            }
            return "Status has Changed";
        }

        return "ERROR: some error has intercept the operation.";
    }

    /**
     * Change the status of Artwork model with the param 'id'
     * @param $id integer The Artwork ID to change it status
     * @return string
     * @throws NotFoundHttpException
     * @throws \yii\db\Exception
     */
    public function actionAvailability($id)
    {
        if (Yii::$app->request->getIsAjax()) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            if (($model = $this->findModel($id)) !== null) {
                Yii::$app->db->createCommand()
                    ->update(Artwork::tableName(), [
                        'availability' => $model->isAvailable() ? Artwork::UNAVAILABILITY_STATUS: Artwork::AVAILABILITY_STATUS
                    ], ['id' => $id])->execute();

            }
            return "Availability has Changed";
        }

        return "ERROR: some error has intercept the operation.";
    }

    /** Manage the save or replace file related with an Artwork model
     * @param Artwork $model
     * @return bool|int
     * @throws \yii\base\Exception
     * @throws \yii\db\Exception
     */
    protected function manageFiles(Artwork $model)
    {
        $route =  '../../common/resources/artwork_files/Artwork_' . $model->id . "/";
        if (!file_exists($route)) {
            FileHelper::createDirectory($route, 0777);
        }

        if (isset($model->file)) {
            if (isset($model->file_name) && file_exists($route . $model->file_name)) {
                unlink($route . $model->file_name);
            }
            $model->file_name = "ArtworkFile_" . time() . "." . $model->file->getExtension();
            $model->file->saveAs($route . $model->file_name);
            return Yii::$app->db->createCommand()
                ->update(Artwork::tableName(), ['file_name' => $model->file_name], ['id' => $model->id])->execute();
        }

        return true;
    }
}

frontend/controllers/ArtworkController.php
<?php

namespace frontend\controllers;

use common\models\ArtBlogBase;
use frontend\assets\AppAsset;
use Yii;
use frontend\models\Artwork;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\View;

/**
 * ArtworkController implements the CRUD actions for Artwork model.
 */
class ArtworkController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Artwork models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Artwork::find(),
        ]);
        $artworks = \backend\models\Artwork::find()->where(['status' =>ArtBlogBase::STATUS_ACTIVE])->all();
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'artworks' => $artworks
        ]);
    }

    /**
     * Displays a single Artwork model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $artwork = $this->findModel($id);
        return $this->render('view', [
            'id' => $id,
            'artwork' => $artwork
        ]);
    }

    /**
     * Creates a new Artwork model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Artwork();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Artwork model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Artwork model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Artwork model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Artwork the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = \backend\models\Artwork::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/artwork/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\ArtworkSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="artwork-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'author_id') ?>

    <?= $form->field($model, 'artwork_type_id') ?>

    <?= $form->field($model, 'exhibition_id') ?>

    <?php // echo $form->field($model, 'technique_id') ?>

    <?php // echo $form->field($model, 'm_unit_id') ?>

    <?php // echo $form->field($model, 'file_name') ?>

    <?php // echo $form->field($model, 'abstract') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'release_date') ?>

    <?php // echo $form->field($model, 'availability') ?>

    <?php // echo $form->field($model, 'quantity') ?>

    <?php // echo $form->field($model, 'price') ?>

    <?php // echo $form->field($model, 'raiting') ?>

    <?php // echo $form->field($model, 'width') ?>

    <?php // echo $form->field($model, 'height') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/artwork/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Artwork */

$this->title = 'Crear Obra';
$this->params['breadcrumbs'][] = ['label' => 'Obras', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="artwork-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/artwork/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\ArtworkSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Obras';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="artwork-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Crear Obra', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(['id'=>'artworkGrid']); ?>
    
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'options' => [
            'class' => 'table-responsive'
        ],
        'columns' => [
            [
                'attribute' => 'id',
                'value' => 'id',
                'contentOptions' => ['style' => 'width:5%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ],
            [
                'attribute' => 'name',
                'value' => 'name',
                'contentOptions' => ['style' => 'width:10%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ],
            [
                'attribute' => 'artwork_type_id',
                'value' => 'artwork_type_id',
                'contentOptions' => ['style' => 'width:8%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ],
            [
                'attribute' => 'exhibition_id',
                'value' => 'exhibition_id',
                'contentOptions' => ['style' => 'width:10%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ],
            [
                'attribute' => 'technique_id',
                'value' => 'technique_id',
                'contentOptions' => ['style' => 'width:10%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ],
            [
                'attribute' => 'availability',
                'filter' => ["1" => "Disponible", "0" => "No Disponible"],
                'value' => function (\backend\models\Artwork $model) {
                    $url = \yii\helpers\Url::to(['/artwork/availability', 'id' => $model->id]);
                    return \kartik\widgets\SwitchInput::widget([
                        'name' => 'availability',
                        'value' => $model->availability,
                        'pluginOptions' => [
                            'size' => 'mini',
                            'onText' => '<i class="glyphicon glyphicon-ok"></i>',
                            'offText' => '<i class="glyphicon glyphicon-remove"></i>',
                            'onColor' => 'success',
                            'offColor' => 'danger'
                        ],
                        'pluginEvents' => [
                            "switchChange.bootstrapSwitch" => "function() { 
                                    $.ajax('$url', {
                                        type: 'POST'
                                    }).done(function(data) {
                                        console.log(data);
                                        $.pjax.reload({container: '#artworkGrid'});
                                    });
                                }",
                        ]
                    ]);
                },
                'format' => 'raw',
                'contentOptions' => ['style' => 'width:8%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ],
            [
                'attribute' => 'quantity',
                'value' => 'quantity',
                'contentOptions' => ['style' => 'width:10%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ],
            [
                'attribute' => 'status',
                'filter' => ["1" => "Activo", "0" => "Inactivo"],
                'value' => function (\backend\models\Artwork $model) {
                    $url = \yii\helpers\Url::to(['/artwork/status', 'id' => $model->id]);
                    return \kartik\widgets\SwitchInput::widget([
                        'name' => 'status',
                        'value' => $model->status,
                        'pluginOptions' => [
                            'size' => 'mini',
                            'onText' => '<i class="glyphicon glyphicon-ok"></i>',
                            'offText' => '<i class="glyphicon glyphicon-remove"></i>',
                            'onColor' => 'success',
                            'offColor' => 'danger'
                        ],
                        'pluginEvents' => [
                            "switchChange.bootstrapSwitch" => "function() { 
                                    $.ajax('$url', {
                                        type: 'POST'
                                    }).done(function(data) {
                                        console.log(data);
                                        $.pjax.reload({container: '#artworkGrid'});
                                    });
                                }",
                        ]
                    ]);
                },
                'format' => 'raw',
                'contentOptions' => ['style' => 'width:8%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Acciones',
                'contentOptions' => ['style' => 'width:6%; text-align:center'],
                'headerOptions' => [
                    'style' => 'text-align:center',
                ],
            ]
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

backend/views/artwork/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Artwork */

$this->title = 'Actualizar Obra: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Obras', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Actualizar';
?>
<div class="artwork-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/artwork/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Artwork */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Artworks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="artwork-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Crear', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Volver', ['index'], ['class' => 'btn btn-default']) ?>
        <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger pull-right',
            'data' => [
                'confirm' => 'Seguro desea eliminar este elemento?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'file_name',
                'value' => Html::img($model->generateFileRoute(),
                    ['alt' => $model->name, 'title' => $model->name, 'style'=>'width: 200px']),
                'format' => 'raw'
            ],
            'name',
            'author_id',
            'artwork_type_id',
            'exhibition_id',
            'technique_id',
            'm_unit_id',
            'abstract',
            [
                'attribute' => 'description', 
                'value' => $model->description,
                'format' => 'html'
            ],
            'release_date',
            [
                'attribute' => 'availability',
                'value' => function (\backend\models\Artwork $model) {
                    $url = \yii\helpers\Url::to(['/artwork/availability', 'id' => $model->id]);
                    return \kartik\switchinput\SwitchInput::widget([
                        'name' => 'status',
                        'value' => $model->status,
                        'pluginOptions' => [
                            'size' => 'mini',
                            'onText' => 'En venta',
                            'offText' => 'No Disponible',
                            'onColor' => 'success',
                            'offColor' => 'danger'
                        ],
                        'pluginEvents' => [
                            "switchChange.bootstrapSwitch" => "function() {
                                        $.ajax('$url', {
                                            type: 'POST'
                                        }).done(function(data) {
                                            console.log(data);
                                        });
                                    }",
                        ]
                    ]);
                },
                'format' => 'raw'
            ],
            'quantity',
            'price',
            'raiting',
            'width',
            'height',
            'created_at',
            'updated_at',
            [
                'attribute' => 'status',
                'value' => function (\backend\models\Artwork $model) {
                    $url = \yii\helpers\Url::to(['/artwork/status', 'id' => $model->id]);
                    return \kartik\switchinput\SwitchInput::widget([
                        'name' => 'status',
                        'value' => $model->status,
                        'pluginOptions' => [
                            'size' => 'mini',
                            'onText' => 'Activo',
                            'offText' => 'Inactivo',
                            'onColor' => 'success',
                            'offColor' => 'danger'
                        ],
                        'pluginEvents' => [
                            "switchChange.bootstrapSwitch" => "function() {
                                        $.ajax('$url', {
                                            type: 'POST'
                                        }).done(function(data) {
                                            console.log(data);
                                        });
                                    }",
                        ]
                    ]);
                },
                'format' => 'raw'
            ],
        ],
    ]) ?>

</div>